//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MyIE9.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MyIE9                       102
#define IDD_PROPPAGE_SPECIAL            102
#define IDS_MyIE9NSHANDLE_DESC          103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MyIE9NSHandle               105
#define IDS_IMG_EXISTED                 105
#define IDD_PROPPAGE_GENERAL            106
#define IDS_IMG_SAVE_TO                 106
#define IDD_URL_FILTER                  107
#define IDS_NOT_DROP_IMG                107
#define IDS_DROP_IMG_HERE               108
#define IDS_TYPE_ICON                   108
#define IDS_SELECT_PATH                 109
#define IDS_CLEAN_COLLECTOR             110
#define IDS_TYPE_EXTOOL                 111
#define IDS_TYPE_QUICKSAVE              112
#define IDS_TYPE_SOUND                  113
#define IDS_TYPE_OPENFILE               114
#define IDS_TYPE_COLLECTOR              115
#define IDS_EMPTY                       116
#define IDS_TYPE_EXE                    117
#define IDS_FTP                         118
#define IDS_DRAG                        119
#define IDS_CONFIRM_IE_DOWN             120
#define IDR_MAINFRAME                   128
#define IDR_MyIE9YPE                    129
#define IDR_MFCIETYPE                   129
#define IDS_SHLWAPI_FAIL                130
#define IDR_MFCAVI                      131
#define IDS_UNTITLED                    131
#define IDR_FONT_POPUP                  132
#define IDS_CLOSE_ALL_CONF              132
#define IDR_FAVORITES_POPUP             133
#define IDS_POPUP_CONF                  133
#define IDS_CONFIRM_EXIT                133
#define IDS_FAIL_ADDR_BOOK              134
#define IDB_BITMAP1                     135
#define IDS_FAIL_EMAIL                  135
#define IDB_FAVMENU                     135
#define IDS_CLEAN_ALL                   136
#define IDS_DEFAULT_WEB_PROXY           137
#define IDS_NO_PROXY                    138
#define IDS_PROXY_FAIL                  139
#define IDR_RTAB                        140
#define IDS_CHANGE_POS                  140
#define IDS_NO_IE_PROXY                 140
#define IDD_POPUPLIST                   141
#define IDS_UTIL_FAIL                   141
#define IDD_SET_PROXY                   142
#define IDS_TITLE_HIS                   142
#define IDD_UN_POPUPLIST                142
#define IDS_TITLE_SEARCH                143
#define IDR_ENCODING                    144
#define IDS_WEEKS_AGO                   144
#define IDD_EXTERN_UTIL                 145
#define IDS_SUNDAY                      145
#define IDD_INPUT_UTIL                  146
#define IDS_MONDAY                      146
#define IDS_TUESDAY                     147
#define IDB_BITMAP2                     148
#define IDS_WEDNESDAY                   148
#define IDB_HISTORY                     148
#define IDS_THURSDAY                    149
#define IDS_FRIDAY                      150
#define IDR_SEARCH                      150
#define IDS_SATURDAY                    151
#define IDS_TODAY                       152
#define IDS_LAST_WEEK                   153
#define IDS_USE_PROXY                   154
#define IDS_LINKS                       155
#define IDS_STARTUP                     156
#define IDS_UNSET_START_FOLDER          156
#define IDB_BITMAP3                     157
#define IDS_SPACES                      157
#define IDB_FAVORITES                   157
#define IDS_NO_WEB_PROXY                157
#define IDB_BITMAP4                     158
#define IDS_WARNING                     158
#define IDR_RFAV_URL                    159
#define IDS_VTILE                       159
#define IDR_RFAV_FOLDER                 160
#define IDS_HTILE                       160
#define IDB_BITMAP5                     161
#define IDS_WEB_TRANS_PROXY             161
#define IDB_BITMAP6                     162
#define IDS_PROXY                       162
#define IDB_SYSMENU                     162
#define IDR_SPEED                       163
#define IDS_ENCODE                      163
#define IDR_F2F12                       164
#define IDS_SEARCH_SELECT               164
#define IDS_NOT_URL                     165
#define IDD_SET_KEY                     165
#define IDS_OPEN_SELECT                 165
#define IDS_CONFIRM_DEL                 167
#define IDD_SET_ALIAS                   168
#define IDS_PROXY_ADDED                 168
#define IDD_INPUT_ALIAS                 169
#define IDS_RESUME                      169
#define IDD_CUSTOMIZE                   170
#define IDS_IMPORT_PROXY                170
#define IDD_MyIE9OPTION                 171
#define IDS_COMFIRM_CATE_DEL            171
#define IDD_STICKNAME                   172
#define IDS_CANT_MOVE_PROXY             172
#define IDD_FILEOPEN                    173
#define IDS_DEFAULT_WEBP_NAME           173
#define IDD_PASSWORD                    174
#define IDS_INVALIDSEARCHNAME           174
#define IDB_BITMAP7                     175
#define IDS_NEEDKEYSTRING               175
#define IDB_GOTO                        175
#define IDB_BITMAP8                     176
#define IDS_SAVEDFORM                   176
#define IDB_BITMAP9                     177
#define IDS_MyIE9SHEET                  177
#define IDB_REFRESH                     177
#define IDI_TRAY                        178
#define IDS_DEFAULTPOS                  178
#define IDS_FILL_FORM_COUNT             178
#define IDS_SAVEIMAGEFAIL               179
#define IDI_ICON1                       180
#define IDS_FILTERSHEET                 180
#define IDD_ORG_GROUP                   181
#define IDD_GROUP_URL                   182
#define IDD_PROXY                       183
#define IDR_HIS_FOLDER                  185
#define IDR_HIS_URL                     186
#define IDD_SETREFRESH                  188
#define IDB_COLDSM                      189
#define IDB_HOTSM                       190
#define IDD_SELPROXYCAT                 191
#define IDB_BITMAP10                    193
#define IDB_PROXY                       193
#define IDB_BITMAP11                    194
#define IDB_MAIN                        194
#define IDD_QUICKSEARCH                 195
#define IDD_INPUT_QUICKSEARCH           196
#define IDI_SECURE                      198
#define IDB_BITMAP12                    199
#define IDB_BITMAP13                    200
#define IDB_STATUS                      200
#define IDD_COLLECTOR                   201
#define IDD_DOWNLOAD                    202
#define IDD_LINKLIST                    203
#define IDC_POINTER_DRAG                204
#define IDD_PROPPAGE_WINDOW             205
#define IDD_PROPPAGE_TAB                206
#define IDD_PROPPAGE_STARTUP            207
#define IDD_PROPPAGE_DOWNLOAD           208
#define IDD_PROPPAGE_OTHERS             209
#define IDD_ADDURLHERE                  211
#define IDD_PROPPAGE_SAVE               213
#define IDB_BITMAP14                    217
#define IDB_SAVEIMG                     217
#define IDB_TAB                         226
#define IDD_SELECT_URL                  227
#define IDD_PROPPAGE_MOUSE              228
#define IDB_HOTTOOL                     230
#define IDB_COLDTOOL                    231
#define IDB_HOTTOOLSMALL                233
#define IDB_COLDTOOLSMALL               234
#define IDB_BITMAP15                    235
#define IDB_MENUICON                    239
#define IDB_MENU                        240
#define IDB_SYSMENUDISABLE              245
#define IDI_SAVE                        246
#define IDI_ICON2                       246
#define IDI_PAGE                        249
#define IDB_COLLECTOR                   250
#define IDB_COLLECTOR_TOOL              250
#define IDB_LAKE                        256
#define IDB_COLLECT                     257
#define IDC_POINTER_DRAG_PAGE           257
#define IDB_COLLECTOR_STATUS            257
#define IDB_SEARCH                      258
#define IDD_MYOPTION                    260
#define IDB_COLDTOOLBAR                 261
#define IDB_HOTTOOLBAR                  262
#define IDB_MYOPTION                    262
#define IDB_OPTION                      264
#define IDR_TRAYMENU                    267
#define IDD_MONITOR                     268
#define IDB_MONITOR                     269
#define IDD_PROPPAGE_GESTURE            269
#define IDI_LINKLIST                    281
#define IDB_LINKLIST                    282
#define IDD_GROUP_WINDOW                283
#define IDD_GROUP_SELECT                284
#define IDI_SECU                        286
#define IDI_NORMAL                      290
#define IDD_POPUP_CONFIRM               291
#define IDD_LAST_CLOSE                  294
#define IDD_ADD_POPUP                   295
#define IDD_WINDOW_MANAGER              296
#define IDD_INPUT                       299
#define IDB_FAV_EXP                     300
#define IDD_SET_FORM_DATA               301
#define IDD_PROPPAGE_TOOLBAR            302
#define IDD_SET_UNDO_CLOSE              303
#define IDD_SAPREFS                     306
#define IDD_PROPPAGE_MENU               308
#define IDD_PROPPAGE_START              309
#define IDR_DRAG_IMG                    309
#define IDD_PROPPAGE_DELETE             310
#define IDD_PROPPAGE_STATUSBAR          311
#define IDR_DRAG_LINK                   311
#define IDD_PROPPAGE_CONFIRM            312
#define IDR_DRAG_TEXT                   312
#define IDD_PROPPAGE_COLLECTOR          313
#define IDR_RTAB_TOP                    313
#define IDD_PROPPAGE_TABSTYLE           314
#define IDD_CLEAN_ALL                   315
#define IDD_PROPPAGE_FTP                316
#define IDD_SORT_SAVE                   317
#define IDD_SELECT_LANG                 318
#define IDD_FLYLIST                     319
#define IDD_ADD_FLY                     320
#define IDB_TASKBAR                     327
#define IDR_RMENU_EDIT                  333
#define IDS_WEB_TUTORIAL                736
#define IDS_ONLINE_SUPPORT              737
#define IDS_FREE_STUFF                  738
#define IDS_GET_FASTER_INTERNET_ACCESS  741
#define IDS_FREQUENTLY_ASKED_QUESTIONS  742
#define IDS_INTERNET_START_PAGE         743
#define IDS_SEND_FEEDBACK               744
#define IDS_BEST_OF_THE_WEB             745
#define IDS_SEARCH_THE_WEB              746
#define IDS_MICROSOFT_HOME_PAGE         747
#define IDS_BACK                        748
#define IDS_FORWARD                     749
#define IDS_STOP                        750
#define IDS_REFRESH                     751
#define IDS_HOME                        752
#define IDS_SEARCH                      753
#define IDS_FAVORITES                   754
#define IDS_PRINT                       755
#define IDS_FONT                        756
#define IDS_ADDRESS                     757
#define ID_KEYWORD                      758
#define IDS_MY_COMPUTER                 759
#define IDS_SET_DEFAULT                 760
#define IDS_TITLE_FAVORITE              761
#define IDS_FAV_ADD                     762
#define IDS_FAV_ORG                     763
#define IDS_CHANNEL                     764
#define IDS_CHANNEL_E                   765
#define IDS_OPEN_ALL_FAV                766
#define IDS_NEW_WINDOW                  767
#define IDS_IMAGE                       768
#define IDS_SP_INVALID                  769
#define IDS_SP_SLOWER                   770
#define IDS_SP_SLOW                     771
#define IDS_SP_NOR                      772
#define IDS_SP_FAST                     773
#define IDS_SP_FASTER                   774
#define IDS_FAV_MOST                    776
#define IDS_ALIAS                       777
#define IDS_SEPARATOR                   778
#define IDS_CANT_DO                     779
#define IDS_EX_TOOL                     780
#define IDS_TITLE_SHELL                 781
#define IDS_TITLE_RESOURCE              782
#define IDS_ROWSE_MODE                  783
#define IDS_AUTO_SCROLL                 784
#define IDS_SAVE_AS                     785
#define IDS_AUTOFILTER                  786
#define IDS_ADDFAV                      787
#define IDS_FZQK                        788
#define IDS_PAGE_SAVED                  789
#define IDS_TEXT_SAVED                  790
#define IDC_ENABLE_POPUP                1000
#define IDC_KILL_LIST_WIN               1000
#define IDC_INSERT                      1002
#define IDC_EDIT                        1003
#define IDC_DELETE                      1004
#define IDC_TEST                        1005
#define IDC_DELETE_SEARCH               1005
#define IDC_USER_PROXY                  1006
#define IDC_UN_INSERT                   1006
#define IDC_EDIT_SEARCH                 1006
#define IDC_PROXY_LIST                  1007
#define IDC_UN_DELETE                   1007
#define IDC_USE_WEB_PROXY               1008
#define IDC_UN_EDIT                     1008
#define IDC_DELETE_CURRENT              1008
#define IDC_WEB_PRO_LIST                1009
#define IDC_DELETE_CURRENT_SEARCH       1010
#define IDC_EXTERN_UTIL                 1012
#define IDC_ADD_UTIL                    1013
#define IDC_MOD_UTIL                    1014
#define IDC_DEL_UTIL                    1015
#define IDC_NAME                        1016
#define IDC_COMMAND                     1017
#define IDC_NAME2                       1017
#define IDC_ICON_PATH                   1017
#define IDC_BROWSER_FILE                1018
#define IDC_EDIT1                       1019
#define IDC_PARAM                       1019
#define IDC_PATH                        1020
#define IDC_BROWSER_PATH                1021
#define IDC_PROXY_NEW                   1028
#define IDC_PROXY_DEL                   1029
#define IDC_WEB_PROXY_NEW               1030
#define IDC_WEB_PROXY_DEL               1031
#define IDC_SPIN1                       1032
#define IDC_SPIN2                       1033
#define IDC_SPIN3                       1034
#define IDC_SPIN4                       1035
#define IDC_LIST1                       1040
#define IDC_KEYLIST                     1041
#define IDC_UPDATE                      1043
#define IDC_CLEAN                       1044
#define IDC_APPEND                      1044
#define IDC_DEL                         1046
#define IDC_NEW                         1047
#define IDC_URL                         1048
#define IDC_ALIAS                       1049
#define IDC_FORM                        1049
#define IDC_CURBTN                      1050
#define IDC_ADD                         1051
#define IDC_REMOVE                      1052
#define IDC_MOVEUP                      1054
#define IDC_MOVWDOWN                    1055
#define IDC_AVABTN                      1056
#define IDC_DLIMG                       1057
#define IDC_DLSOUND                     1058
#define IDC_DLVIDEO                     1059
#define IDC_DLJS                        1060
#define IDC_DLAPPLET                    1061
#define IDC_DLACTIVEX                   1062
#define IDC_SKINPATH                    1063
#define IDC_MAXCHARS                    1064
#define IDC_MAXWIDTH                    1065
#define IDC_COMFIRMEXIT                 1066
#define IDC_SAVEPATH                    1067
#define IDC_COMFIRMEXIT_DOWNING         1067
#define IDC_CE2                         1068
#define IDC_SAVEPATH_SORT               1068
#define IDC_CSE1                        1069
#define IDC_CSE2                        1070
#define IDC_SE1                         1071
#define IDC_SE2                         1072
#define IDC_CE1                         1073
#define IDC_MAXMENU                     1074
#define IDC_SINGLEMENU                  1075
#define IDC_SYSTRAY                     1076
#define IDC_SHOW_TRAY                   1076
#define IDC_MAXMENU_OTHER               1076
#define IDC_MAXWIN                      1077
#define IDC_STICKNAME                   1078
#define IDC_KEEPSILENT                  1079
#define IDC_MINWIDTH                    1080
#define IDC_TOP_CLOSE                   1080
#define IDC_BROWSE                      1081
#define IDC_FORBID_UPDATE               1081
#define IDC_ADDRESS                     1082
#define IDC_ENABLE_IE8MODE              1082
#define IDC_AUTO_HIDE_FAVORITES         1083
#define IDC_AlwaysIEMenuRightClickImg   1084
#define IDC_REM_PSW                     1085
#define IDC_DirectOpenForOneWord        1085
#define IDC_PASSWORD                    1086
#define IDC_STARTUP                     1087
#define IDC_INTERVAL                    1088
#define IDC_CONFIRMCLOSEALL             1089
#define IDC_ONLYONE                     1090
#define IDC_CONFIRMCLOSEALL_KEEPCUR     1090
#define IDC_BYPASS                      1091
#define IDC_CONFIRMCLOSELOCK            1091
#define IDC_CONFIRM_UNSAFE_PAGE         1092
#define IDC_CONFIRM_DUP_PAGE            1093
#define IDC_CONFIRM_MIX_CONTENT_ALERT   1093
#define IDC_NEW_GROUP                   1094
#define IDC_DEL_GROUP                   1095
#define IDC_URL_LIST                    1101
#define IDC_GROUP_LIST                  1102
#define IDC_UN_URL_LIST                 1102
#define IDC_BLANKWIN                    1104
#define IDC_HOME                        1105
#define IDC_START_MODE                  1105
#define IDC_CURWIN                      1106
#define IDC_STATUS_DISP                 1106
#define IDC_START_MODE2                 1106
#define IDC_BLANKWIN2                   1107
#define IDC_CLIPBOARD                   1107
#define IDC_START_MODE3                 1107
#define IDC_ALLOW_DBC                   1108
#define IDC_HOME2                       1108
#define IDC_SELECT_STRING               1108
#define IDC_START_MODE4                 1108
#define IDC_GROUP_PATH                  1109
#define IDC_CURWIN2                     1109
#define IDC_START_MODE5                 1109
#define IDC_MODIFYPROXY                 1110
#define IDC_FAV_PATH                    1110
#define IDC_START_MODE6                 1110
#define IDC_WEBPROXY_MODIFY             1111
#define IDC_START_MODE7                 1111
#define IDC_LINK_PATH                   1111
#define IDC_PROXY                       1112
#define IDC_PAGE_SIZE                   1112
#define IDC_START_MODE8                 1112
#define IDC_SPEED                       1113
#define IDC_START_MODE9                 1113
#define IDC_EDIT_USER_APP_TITLE         1113
#define IDC_COLOR_ICON                  1114
#define IDC_TEXT_OPT                    1115
#define IDC_DISPLAY_OPENALL             1116
#define IDC_REFINTERVAL                 1117
#define IDC_SHOW_HIDDEN                 1117
#define IDC_ICON_OPT                    1118
#define IDC_PROXYCATS                   1119
#define IDC_CLEAR                       1120
#define IDC_CATES                       1121
#define IDC_NEWCATE                     1122
#define IDC_DELCATE                     1124
#define IDC_CLOSEUTIL                   1125
#define IDC_AUTO_FILTER                 1126
#define IDC_FILTER_DUP                  1127
#define IDC_KILL_DUP_WIN                1127
#define IDC_SEACHLIST                   1129
#define IDC_SEARCHENGINE                1133
#define IDC_RICHEDIT1                   1134
#define IDC_TXT                         1135
#define IDC_IMAGE                       1136
#define IDC_NO_TOOL                     1137
#define IDC_FILTER                      1137
#define IDC_NETANTS                     1138
#define IDC_FLASHGET                    1139
#define IDC_FILEEXT                     1140
#define IDC_SELECTTOOLS                 1141
#define IDC_DISP_ANIICON                1142
#define IDC_COMPACTFAVBAR               1143
#define IDC_FAV_SHOW_URL                1144
#define IDC_MULTILINE_TAB               1146
#define IDC_AUTOFIT_TAB                 1147
#define IDC_DISP_NEXT_TAB               1148
#define IDC_NEW_ADDRESS                 1149
#define IDC_FAV_LNK                     1150
#define IDC_HISTORY                     1151
#define IDC_LOCALFILE                   1152
#define IDC_LINKSINPAGE                 1153
#define IDC_ACTIVATE_NEWWIN             1154
#define IDC_DEFAULT_SEQ                 1155
#define IDC_CLOSE_SEQUENCE              1155
#define IDC_NEXT_SEQ                    1156
#define IDC_NEW_SEQUENCE                1156
#define IDC_PRE_SEQ                     1157
#define IDC_START_BLANK                 1158
#define IDC_START_HOME                  1159
#define IDC_START_LASTVISIT             1160
#define IDC_START_STARTFAV              1161
#define IDC_START_STARTGROUP            1163
#define IDC_TAB_TOP                     1164
#define IDC_BOTTOM_TAB                  1165
#define IDC_LDBCLICK                    1166
#define IDC_MCLIK                       1167
#define IDC_LINK_L                      1167
#define IDC_LINK_UP                     1167
#define IDC_PLAY_ANIMATION              1168
#define IDC_LEFT_RIGHT                  1168
#define IDC_IMAGEPATH                   1169
#define IDC_LINK_L_CTRL                 1169
#define IDC_LINK_LEFT                   1169
#define IDC_IMG_L                       1170
#define IDC_PLAY_FLASH                  1170
#define IDC_IMG_UP                      1170
#define IDC_FOLDER                      1171
#define IDC_IMG_L_CTRL                  1171
#define IDC_IMG_LEFT                    1171
#define IDC_ADDFAV                      1172
#define IDC_TXT_L                       1172
#define IDC_TXT_UP                      1172
#define IDC_MOUSEGESTURE                1173
#define IDC_TXT_L_CTRL                  1173
#define IDC_TXT_LEFT                    1173
#define IDC_LOCKHOME                    1174
#define IDC_IMG_R                       1174
#define IDC_IMG_DOWN                    1174
#define IDC_AUTOSAVE                    1175
#define IDC_IMG_L3                      1175
#define IDC_LINK_R                      1175
#define IDC_FORBID_MAIN_TITLE           1175
#define IDC_LINK_DOWN                   1175
#define IDC_CATEWITHSITE                1176
#define IDC_TXT_L_ALT                   1176
#define IDC_TXT_RIGHT                   1176
#define IDC_IMG_CATEWITHSITE            1177
#define IDC_IMG_ALT                     1177
#define IDC_IMG_RIGHT                   1177
#define IDC_LINK_ALT                    1178
#define IDC_LINK_RIGHT                  1178
#define IDC_NAME_BY_TITLE               1178
#define IDC_RCLIK                       1179
#define IDC_TXT_L_SHIFT                 1179
#define IDC_TXT_DOWN                    1179
#define IDC_SAVE_BY_DATE                1179
#define IDC_SHOW_SORT_DLG               1180
#define IDC_URL_FILTER                  1181
#define IDC_START_NONE                  1185
#define IDC_FLATBUTAB                   1186
#define IDC_ADDRS                       1188
#define IDC_DELETEALL                   1190
#define IDC_LOCAL_DOWN_ALL              1191
#define IDC_DELETEALL_SEARCH            1191
#define IDC_LOCAL_WORK_OFFLINE          1192
#define IDC_GET_SAVEPATH                1195
#define IDC_SELECT_ALL                  1196
#define IDC_GET_SAVEPATH_SORT           1196
#define IDC_GET_IMAGEPATH               1197
#define IDC_SELECT_NONE                 1197
#define IDC_SELECT_BEFORE               1198
#define IDC_LIST_URL                    1199
#define IDC_SELECT_AFTER                1199
#define IDC_EMAIL                       1200
#define IDC_COPY_URL                    1200
#define IDS_FILETYPES                   1201
#define IDC_HOMEPAGE                    1201
#define IDC_CHECK_ODD                   1201
#define IDC_CHECK_EVEN                  1202
#define IDC_CHECK2                      1203
#define IDC_DEFAULT_FAVPATH             1203
#define IDC_DELETE_CHECK                1203
#define IDC_WHEEL_TAB                   1203
#define IDC_ENABLE_POP_WIN              1203
#define ID_NEW_ADDRESS                  1203
#define IDC_OFFLINE                     1203
#define IDC_USE_SPECIAL                 1203
#define IDC_LOAD_LAST_CLOSE             1203
#define IDC_OUTPUT_SAVE_FILTER          1203
#define IDC_TYPE                        1203
#define IDC_AUTO_SUBMIT                 1203
#define IDC_TYPED_ADDRS                 1204
#define ID_NEW_HISTORY                  1204
#define IDC_WHEEL_ON_TAB                1204
#define IDC_OUTPUT_SAVE_PAGE            1204
#define ID_TB_LABEL                     1205
#define IDC_TYPED_SEARCH                1205
#define IDC_OUTPUT_SAVE_IMG             1205
#define IDC_DEFAULT_LINKPATH            1205
#define ID_TB_GO                        1206
#define ID_ADDRESS_BUTTON               1206
#define IDC_OUTPUT_AUTO_CLEAN           1206
#define IDC_ACTIVATE_NEW_ADDRESS        1206
#define ID_ACTIVE_FILE_NEW              1207
#define ID_SEARCH_BUTTON                1207
#define IDC_OUTPUT_SAVE_TEXT            1207
#define IDC_SHOW_INDEX                  1208
#define ID_TB_COMBO_ICON                1208
#define IDC_OUTPUT_SAVE_URL_FILTER      1208
#define IDC_GET_SKINPATH                1209
#define IDC_SHOW_DOT                    1209
#define IDC_GET_GROUPPATH               1210
#define IDC_SHOW_READ                   1210
#define IDC_GET_FAVPATH                 1211
#define IDC_SHOW_FAVICON                1211
#define IDC_CHARSET                     1212
#define IDC_GET_LINKPATH                1212
#define IDC_SHOW_X                      1212
#define IDC_OPEN_IE_FAV                 1213
#define IDC_DEFAULT_CHARSET             1214
#define IDC_SET_TO_IE_FAV               1214
#define IDC_DOWN_ALL                    1215
#define IDC_MBUTTON_DOWN                1216
#define IDC_DOWN_MANAGER                1216
#define IDC_GESTURE_UP_DOWN             1217
#define IDC_RMOUSE_NONE                 1218
#define IDC_RMOUSE_DRAG                 1219
#define IDC_RMOUSE_GESTURE              1220
#define IDC_GESTURE_UP_LEFT             1221
#define IDC_CHECK1                      1222
#define IDC_LBUTTON_DOWN                1222
#define IDC_OPEN_FOLDER_OUT             1222
#define IDC_MIN_TRAY                    1222
#define IDC_KILL_AUTO_WIN               1222
#define IDC_OPEN                        1222
#define IDC_STATE                       1222
#define IDC_NOT_POP_CONFIRM             1222
#define IDC_SHOW_GROUP_MEMBER           1222
#define IDC_CLOSE_PAGE                  1222
#define IDC_OPEN_IN_NEW                 1222
#define IDC_ENCRYPT_STRING_ITEM         1222
#define IDC_FS_TOOL                     1222
#define IDC_OUTPUT_SAVE_TIME            1222
#define IDC_SHOW_GESTURE                1222
#define IDC_GESTURE_UP_RIGHT            1223
#define IDC_CLOSE_TRAY                  1223
#define IDC_NOT_CONFIRM_POPUP           1223
#define IDC_ADDTO_POP_LIST              1223
#define IDC_CLOSE_ALL_BEFORE_NEW_GROUP  1223
#define IDC_DIRECT_OPEN_FILE            1223
#define IDC_AUTO_REFRESH_ACTIVE         1223
#define IDC_FS_EXTOOL                   1223
#define IDC_DATE_SAVE                   1223
#define IDC_GESTURE_DOWN_UP             1224
#define IDC_CLOSE_TRAY_CLOSEALL         1224
#define IDC_FS_ADDRESS                  1224
#define IDC_KEEP_ONEPAGE                1224
#define IDC_GESTURE_DOWN_LEFT           1225
#define IDC_AUTO_RUN                    1225
#define IDC_FS_SEARCH                   1225
#define IDC_MONITOR_CLIP                1225
#define IDC_OPEN_WORD_OUT_IE            1225
#define IDC_GESTURE_DOWN_RIGHT          1226
#define IDC_FS_FAV                      1226
#define IDC_USE_TARGET_FRAME_NAME       1226
#define IDC_KEEP_PAGE_SIZE              1226
#define IDC_FS_LINK                     1227
#define IDC_RELOAD_UNSHOWN_IMAGE        1227
#define IDC_GESTURE_UP                  1228
#define IDC_FS_TAB                      1228
#define IDC_GESTURE_DOWN                1229
#define IDC_FS_SYSMENU                  1229
#define IDC_GESTURE_LEFT                1230
#define IDC_FS_MENU                     1230
#define IDC_GESTURE_RIGHT               1231
#define IDC_FS_STATUS                   1231
#define IDC_RBUTTON_DOWN                1232
#define IDC_FS_TOOL2                    1232
#define IDC_FS_EXTOOL2                  1233
#define IDC_RIGHT_LEFT                  1233
#define IDC_FS_ADDRESS2                 1234
#define IDC_FS_SEARCH2                  1235
#define IDC_TAB1                        1236
#define IDC_FS_FAV2                     1236
#define IDC_TAB                         1236
#define IDC_FS_LINK2                    1237
#define IDC_TAB2                        1237
#define IDC_KEY                         1238
#define IDC_FS_TAB2                     1238
#define IDC_FS_SYSMENU2                 1239
#define IDC_ITEM_LIST                   1240
#define IDC_FS_MENU2                    1240
#define IDC_FS_STATUS2                  1241
#define IDC_MENU_WIN9X                  1242
#define IDC_MENU_WINXP                  1243
#define IDC_EDIT_ABOUT                  1244
#define IDC_ABOUT_ME                    1244
#define IDC_CODE                        1246
#define IDC_GET_KEY                     1247
#define IDC_TRANS                       1248
#define IDC_SCROLLBAR1                  1249
#define IDC_MONITOR_TRANS               1249
#define IDC_STATIC_FAVPATH              1252
#define IDC_FAV_PATH_                   1252
#define IDC_PERCENT                     1253
#define IDC_STATIC_LINKPATH             1253
#define IDC_LINK_PATH_                  1253
#define IDC_LABLE_APP_USER_TITLE        1254
#define IDC_GESTURE                     1257
#define IDC_LIST                        1258
#define IDC_LIST2                       1259
#define IDC_OPENLINK                    1267
#define IDC_OPENSELECTED                1268
#define IDC_RADIO1                      1279
#define IDC_CC_DISABLE                  1279
#define IDC_ADD_NEW_BOTTOM              1279
#define IDC_STYLE_FB                    1279
#define IDC_FTP_OPEN                    1279
#define IDC_CC_RIGHT_KEY                1280
#define IDC_RADIO2                      1280
#define IDC_STYLE_SKIN_TAB              1280
#define IDC_CC_LEFT_KEY                 1281
#define IDC_RADIO3                      1281
#define IDC_STYLE_OK_TAB                1281
#define IDC_HOTKEY                      1283
#define IDC_UPDATE_HOTKEY               1284
#define IDC_THANKS                      1285
#define IDC_STATIC_NAME                 1286
#define IDC_STATIC_URL                  1287
#define ID_NEW_FAV                      1288
#define ID_NEW_LOCAL                    1289
#define ID_NEW_LINKS                    1290
#define IDC_GET_TIME                    1290
#define ID_NEW_HOME                     1291
#define IDC_BLANK_PAGE                  1292
#define IDC_SPIN                        1293
#define IDC_SEARCH_NOTE                 1294
#define IDC_FILTER_TYPE                 1295
#define IDC_PLAY_POPUP_SOUND            1297
#define IDC_FILTER_REFRESH              1298
#define IDC_POPUP_SOUND_PATH            1299
#define IDC_NOT_FILTER_CLICK_DIALOG     1299
#define IDC_MSG                         1304
#define IDC_OUTPUT                      1305
#define IDC_GO_SEARCH                   1306
#define IDC_GO_PROXY_MENU               1306
#define IDC_MSG3                        1306
#define IDC_EDIT_ITEM                   1308
#define IDC_DEL_URL                     1309
#define IDC_DEL_ITEM                    1310
#define IDC_DEL_URL_ALL                 1310
#define IDC_SET_MAIN_PWD                1311
#define IDC_IMPORT_PLUG_IN              1312
#define IDC_SET_FILL_PWD                1312
#define IDC_CLOSE_CLEAN_COOKIES         1313
#define IDC_CLOSE_CLEAN_HISTORY         1314
#define IDC_UP_URL                      1314
#define IDC_CLOSE_CLEAN_CACHE           1315
#define IDC_EDIT_URL                    1315
#define IDC_COPY                        1315
#define IDC_CLOSE_CLEAN_FORM_DATA       1316
#define IDC_CLOSE_CLEAN_TYPED_ADDRESS   1317
#define IDC_OPEN_SELECTED               1317
#define IDC_CLOSE_CLEAN_TYPED_SEARCH    1318
#define IDC_EDIT_TITLE                  1318
#define IDC_STATUS_STRING_FORMAT        1318
#define IDC_CLOSE_CLEAN_UNDO_CLOSE      1319
#define IDC_INFO                        1319
#define IDC_OPEN_CURRENT                1319
#define IDC_DEL_CURRENT                 1320
#define IDC_UN_STATIC                   1321
#define IDC_PAGE_TREE                   1323
#define IDC_DLG_FRAME                   1324
#define IDC_DOWN_TYPE                   1326
#define IDC_SET_DEFAULT                 1327
#define IDC_DOWN_EDIT                   1328
#define IDC_UNSEL_COLOR                 1329
#define IDC_UNSEL_FONT_COLOR            1330
#define IDC_SEL_FONT_COLOR              1331
#define IDC_STYLE_NT                    1332
#define IDC_STYLE_FT                    1333
#define IDC_SEP_COLOR                   1334
#define IDC_DEFAULT_COLOR               1335
#define IDC_SEL_COLOR                   1336
#define IDC_EXE_PATH                    1337
#define IDC_NOT_SORT                    1343
#define IDC_RENAME                      1346
#define IDC_ABOUT                       1347
#define IDC_LANG                        1348
#define IDC_NAME_                       1349
#define IDC_URL_                        1350
#define IDC_AVAI_                       1351
#define IDC_CUR_                        1352
#define IDC_TEXT_                       1353
#define IDC_ICON_                       1354
#define IDC_ALIAS_                      1355
#define IDC_NOTE                        1356
#define IDC_GROUP_                      1357
#define IDC_GENERAL                     1358
#define IDC_EXIT                        1359
#define IDC_CLOSE                       1360
#define IDC_DEFAULT                     1361
#define IDC_SPECIAL                     1362
#define IDC_ALL_                        1363
#define IDC_DOWN_MANAGER_               1364
#define IDC_DOWN_TYPE_                  1365
#define IDC_DOWN                        1366
#define IDC_FTP                         1367
#define IDC_BACK                        1367
#define IDC_FOLDER_                     1368
#define IDC_CLEAN_ALL                   1369
#define IDC_KEY_                        1370
#define IDC_CMD_                        1371
#define IDC_PARAM_                      1372
#define IDC_PATH_                       1373
#define IDC_MEMBER_                     1374
#define IDC_NAVIGATE                    1375
#define IDC_SEARCH                      1376
#define IDC_SKINPATH_                   1377
#define IDC_GROUP_PATH_                 1378
#define IDC_FAV                         1379
#define IDC_MENU_SIZE                   1380
#define IDC_MAXMENU_                    1381
#define IDC_BUTTON                      1382
#define IDC_MAXMENU_OTHER_              1382
#define IDC_DRAG_IMAGE                  1383
#define IDC_DRAG_LINK                   1384
#define IDC_DRAG_TEXT                   1385
#define IDC_LBUTTON_DOWN_               1386
#define IDC_LDBCLICK_                   1387
#define IDC_LEFT_RIGHT_                 1388
#define IDC_MBUTTON_DOWN_               1389
#define IDC_RBUTTON_DOWN_               1390
#define IDC_RIGHT_LEFT_                 1391
#define IDC_IMG_UP_                     1392
#define IDC_IMG_LEFT_                   1393
#define IDC_IMG_DOWN_                   1394
#define IDC_IMG_RIGHT_                  1395
#define IDC_LINK_UP_                    1396
#define IDC_LINK_LEFT_                  1397
#define IDC_LINK_DOWN_                  1398
#define IDC_LINK_RIGHT_                 1399
#define IDC_TXT_UP_                     1400
#define IDC_TXT_DOWN_                   1401
#define IDC_TXT_LEFT_                   1402
#define IDC_TXT_RIGHT_                  1403
#define IDC_DOMAIN                      1404
#define IDC_TRAY                        1405
#define IDC_MENU                        1406
#define IDC_CTRL                        1407
#define IDC_SHIFT                       1408
#define IDC_CTRL_SHIFT                  1409
#define IDC_PAGE                        1410
#define IDC_SAVEPATH_                   1411
#define IDC_SAVEPATH_SORT_              1412
#define IDC_AUTOSAVE_                   1413
#define IDC_PAGE_AUTO                   1414
#define IDC_START                       1415
#define IDC_DISP                        1416
#define IDC_INFO1                       1417
#define IDC_INFO2                       1418
#define IDC_CLICKICON                   1419
#define IDC_INFO3                       1419
#define IDC_WIDTH                       1420
#define IDC_CLICK                       1421
#define IDC_MOUSE                       1422
#define IDC_MAXWIDTH_                   1423
#define IDC_MINWIDTH_                   1424
#define IDC_MAXCHARS_                   1425
#define IDC_MCLIK_                      1426
#define IDC_RCLIK_                      1427
#define IDC_STYLE                       1428
#define IDC_MOUSE2                      1428
#define IDC_COLOR                       1429
#define IDC_TOOLBAR                     1430
#define IDC_FULLSCREEN                  1431
#define IDC_AUTOHIDE                    1432
#define IDC_SEQ                         1433
#define IDC_CONTROL                     1434
#define IDC_TRANSPARENT                 1435
#define IDC_TRANS_                      1436
#define IDC_MONITOR_TRANS_              1437
#define IDC_NEW_WIN                     1438
#define IDC_ACTIVE_NEW                  1439
#define IDC_INTERVAL_                   1440
#define IDC_MAXWIN_                     1441
#define IDC_PROXY_                      1442
#define IDC_SEARCHENGINE_               1443
#define IDC_ITEM                        1444
#define IDC_BYPASS_                     1445
#define IDC_UP                          1448
#define IDC_NEW_SEQUENCE_               1449
#define IDC_LEFT                        1450
#define IDC_CLOSE_SEQUENCE_             1450
#define IDC_RIGHT                       1451
#define IDC_SPEED_                      1452
#define IDC_VER                         1453
#define _IDC_FILENAME                   1455
#define IDC_FILENAME                    1456
#define IDC_LDBCLICK_BLANK              1458
#define IDC_LDBCLICK_BLANK_             1459
#define IDC_RDBCLICK_BLANK              1460
#define IDC_GET_ICON                    1460
#define IDC_RDBCLICK_BLANK_             1461
#define IDC_HOTKEY1                     1461
#define IDC_POP_DELAY                   1463
#define IDC_HIGH                        1464
#define IDC_FILTER_LEVEL                1465
#define IDC_SIMU_DRAG_LINK              1466
#define IDC_KILL_BLANK                  1467
#define IDC_BLANK_CONTENT               1468
#define IDC_DONATE                      1469
#define IDC_COMMAND_                    1470
#define IDC_UN_FLY_STATIC               1472
#define IDC_ENABLE_FLY_CONTENT          1473
#define IDD_UN_FLYLIST                  1474
#define IDC_FILTER_FLY_PAGE             1475
#define IDC_ENABLE_FLY_WHEN_REFRESH     1475
#define IDC_MSG_ADD_FLY_DLG             1476
#define IDC_STATIC_FORM_DLG_TIP         1477
#define IDC_EDIT_HOME_URL               1478
#define IDC_BUTTON_HOME_CUR             1479
#define IDC_BUTTON_HOME_NONE            1480
#define IDC_BUTTON_HOME_BLANK           1481
#define IDC_BUTTON_HOME_GET_IE          1482
#define IDC_COMBO_STARTPAGE             1483
#define IDC_RESTORE                     1484
#define ID_FILE_NEW_BLANK               32772
#define ID_FILE_NEW_CURRENTPAGE         32773
#define ID_FILE_CLOSE_2                 32774
#define ID_FILE_CLOSEALL                32775
#define ID_FILE_CLOSE_1                 32776
#define ID_FILE_SAVEAS                  32777
#define ID_VIEW_STOP                    32778
#define ID_VIEW_REFRESH                 32779
#define ID_FILE_WORKOFFLINE             32780
#define ID_VIEW_ADDRESSBAR              32781
#define ID_VIEW_FONTS_LARGEST           32782
#define ID_VIEW_FONTS_LARGE             32783
#define ID_VIEW_FONTS_MEDIUM            32784
#define ID_VIEW_FONTS_SMALL             32785
#define ID_VIEW_FONTS_SMALLEST          32786
#define ID_GO_BACK                      32787
#define ID_GO_FORWARD                   32788
#define ID_GO_START_PAGE                32789
#define ID_GO_SEARCH_THE_WEB            32790
#define ID_GO_BEST_OF_THE_WEB           32791
#define ID_VIEW_TASKBAR                 32792
#define ID_FAVORITES_DROPDOWN           32793
#define ID_VIEW_SOURCE                  32794
#define ID_FONT_DROPDOWN                32795
#define ID_TOOLS_INTERNETOPTIONS        32796
#define ID_HELP_WEB_TUTORIAL            32798
#define ID_FILE_SAVEHTML                32798
#define ID_ENCODE_DROPDOWN              32799
#define ID_BMODE_DROPDOWN               32800
#define ID_FAVORITES_ADDTOFAVORITES     32803
#define ID_FAVORITES_ORGNIZEFAVORITES   32804
#define ID_FILE_IMPORTFAVORITES         32805
#define ID_FAVORITES_IMPORTFAVORITES    32805
#define ID_FILE_EXPORTFAVORITES         32806
#define ID_FAVORITES_EXPORTFAVORITES    32806
#define ID_OPTIONS_MyIE9OPTIONS         32807
#define ID_OPTIONS_LOADIMAGE            32808
#define ID_OPTIONS_LOADVIDEOS           32809
#define ID_OPTIONS_LOADSOUNDS           32810
#define ID_OPTIONS_LOADANIMATIONS       32811
#define ID_OPTIONS_ALLOWSCRIPTS         32812
#define ID_RTAB_LOCK                    32815
#define ID_RTAB_ADDTOPOPUPFILTER        32816
#define ID_BOGUS                        32817
#define ID_TOOLS_ADDTOPOPUPFILTER       32818
#define ID_TOOLS_EDITPOPUPFILTERLIST    32819
#define ID_TOOLS_EABLEPOPUPFILTER       32820
#define ID_TOOLS_EMAIL                  32821
#define ID_TOOLS_ADDR                   32822
#define ID_TOOLS_ALERT                  32823
#define ID_TOOLS_COOKIE                 32824
#define ID_TOOLS_HISTORY                32825
#define ID_TOOLS_CACHE                  32826
#define ID_TOOLS_ALL                    32827
#define ID_OPTIONS_USE_PROXY            32828
#define ID_OPTIONS_SET_PROXY            32829
#define ID_OPTIONS_USE_WEBP             32830
#define ID_OPTIONS_ALLOWJAVAAPPLET      32832
#define ID_OPTIONS_ALLOWACTIVEX         32833
#define ID_VIEW_ENCODING_WESTERNEUROPEAN 32836
#define ID_VIEW_ENCODING_CHINESESIMPLIFIED 32837
#define ID_VIEW_ENCODING_CHINESETRADITIONAL 32838
#define ID_VIEW_ENCODING_JANESE         32839
#define ID_OPTION_TOP_TAB               32840
#define ID_OPTION_BOT_TAB               32841
#define ID_VIEW_HIS                     32842
#define ID_TOOLS_EXTERNALUTILITIES_UTILITYMANAGER 32843
#define ID_VIEW_EXPLOREBAR_SEARCH       32844
#define ID_VIEW_FULLSCREEN              32845
#define ID_OPTIONS_SETASDEFAULTBROWSER  32846
#define ID_FAV_POPUP                    32847
#define ID_ADDR_DROP                    32848
#define ID_ADDR_FOCUS                   32849
#define ID_FILE_NEW_S                   32852
#define ID_HELP_HELP                    32853
#define ID_OPTIONS_ACTIVENEWWINDOW      32854
#define ID_OPTIONS_MyIE9STARTUP_OPENBLANKPAGE 32855
#define ID_OPTIONS_MyIE9STARTUP_RESUMELASTVISITEDPAGES 32856
#define ID_OPTIONS_MyIE9STARTUP_OPENFAVORITEPAGES 32857
#define ID_RFAV_START                   32858
#define ID_RFAV_COPY                    32859
#define ID_RFAV_DEL                     32860
#define ID_RFAV_PROPERTY                32861
#define ID_RFAV_OPENALL                 32862
#define ID_RFAV_DEL_FOLDER              32863
#define ID_RTAB_CLOSE_OTHER             32864
#define ID_RTAB_ADDFAV                  32865
#define ID_VIEW_LINKS                   32866
#define ID_RFAV_START_FOLDER            32867
#define ID_LINK_POPUP                   32868
#define ID_OPTION_MULTI_TAB             32869
#define ID_MENU_BAR                     32869
#define ID_SYSMENU_BAR                  32870
#define ID_HELP_FORUM                   32871
#define ID_TOOLS_OPENALLLINKS           32872
#define ID_FILE_NEW_CLIP                32873
#define ID_FILE_CLOSE_KEEPCUR           32874
#define ID_HELP_HOMEPAGE                32875
#define ID_VIEW_REFRESHALL              32876
#define ID_OPTION_ALWAYS_NEW            32877
#define ID_OPTIONS_NEWTAB               32878
#define ID_VIEW_STOP_ALL                32879
#define ID_TOOLS_IP                     32881
#define ID_WINDOW_RESTOR                32882
#define ID_MENUITEM32883                32883
#define ID_WINDOW_MIN                   32884
#define ID_VIEW_MENUBAR                 32886
#define ID_TOOLS_SETBACKGROUNDPIC_NONE  32888
#define ID_RFAV_OPEN_NEW                32890
#define ID_FILE_NEWMyIE9                32891
#define ID_FILE_OPENF                   32892
#define ID_VIEW_TOOLBARTEXTLABEL        32893
#define IDS_PASSWORD_ERROR              32893
#define ID_FAVORITES_BEST               32894
#define ID_SP_INVALID                   32895
#define ID_SP_SLOWER                    32896
#define ID_SP_SLOW                      32897
#define ID_SP_NOR                       32898
#define ID_SP_FAST                      32899
#define ID_SP_FASTER                    32900
#define ID_TOOLS_OPENSTART              32901
#define ID_OPTION_AUTOTAB               32902
#define ID_SHORTCUT_ALIAS               32903
#define ID_SHORTCUT_MANALIAS            32904
#define ID_SHORTCUT_USE_SC              32905
#define ID_SHORTCUT_SC                  32906
#define ID_SHORTCUT_MFL                 32907
#define ID_RFAV_MOST_FAV                32908
#define ID_RFAV_ALIAS                   32909
#define ID_F_2                          32913
#define ID_F_3                          32914
#define ID_F_4                          32915
#define ID_F_5                          32916
#define ID_F_6                          32917
#define ID_F_7                          32918
#define ID_F_8                          32919
#define ID_F_9                          32920
#define ID_F_10                         32921
#define ID_F_11                         32922
#define ID_F_12                         32923
#define ID_RFAV_ADDSHORTCUT             32924
#define ID_VIEW_TOOLBARS_CUSTOMIZE      32925
#define ID_OPTIONS_MyIE9GOHOME          32927
#define ID_SHORTCUTS_USE3721            32929
#define ID_RTAB_STICKNAME               32930
#define ID_OPTION_SEQ_DEFAULT           32931
#define ID_OPTION_SEQ_NEXT              32932
#define ID_OPTION_SEQ_PRE               32933
#define ID_TAB_PRE                      32934
#define ID_TAB_NEXT                     32935
#define ID_OPTIONS_URLINSTATUS          32936
#define ID_C_1                          32939
#define ID_C_2                          32940
#define ID_C_3                          32941
#define ID_C_4                          32942
#define ID_C_5                          32943
#define ID_C_6                          32944
#define ID_C_7                          32945
#define ID_C_8                          32946
#define ID_C_9                          32947
#define ID_C_0                          32948
#define ID_RTAB_REFRESH                 32950
#define ID_RTAB_STOP                    32951
#define ID_FILE_PRINTPREVIEW            32952
#define ID_VIEW_FAVS                    32953
#define ID_RFAV_MOST_FOLDER             32954
#define ID_RTAB_PROTECT                 32955
#define ID_RFAVFOLDER_NEW_FOLDER        32956
#define ID_RFAVFOLDER_FIND              32957
#define ID_VIEW_SEARCH                  32958
#define ID_VIEW_EX_TOOL                 32959
#define ID_EDIT_EDIT                    32960
#define ID_MENUITEM32961                32961
#define ID_FILE_STOP_OPENALL            32962
#define ID_FILE_HIDE                    32963
#define ID_VIEW_FOLDER                  32964
#define ID_OPTIONS_OPENLINKINNEWWINDOW  32965
#define ID_OPTIONS_BROWSEMODES_DEFAULT  32966
#define ID_OPTIONS_BROWSEMODES_NEWS     32967
#define ID_OPTIONS_BROWSEMODES_STANDARD 32968
#define ID_VIEW_EXPLOREBAR_RESOURCE     32969
#define ID_TOOLS_AUTOSCROLL_AUTOSCROLLINGAFTERDOWNLOADING 32970
#define ID_TOOLS_AUTOSCROLL_SLOW        32971
#define ID_TOOLS_AUTOSCROLL_MEDIUM      32972
#define ID_TOOLS_AUTOSCROLL_FAST        32973
#define ID_TOOLS_AUTOSCROLL_USEAUTOSCROLLING 32974
#define ID_EDIT_UNDOCLOSE               32975
#define IDS_UNDO_CLOSE                  32976
#define ID_ORGGROUP                     32977
#define ID_ADDTOGROUP                   32978
#define ID_OPTIONS_MyIE9STARTUP_OPENSTARTUPGROUP 32979
#define ID_NEWWINDOW                    32980
#define ID_RFAVFOLDER_RESET             32981
#define ID_NEWWINDOW_FAV                32982
#define ID_NEWWINDOW_HISTORY            32984
#define ID_NEWWINDOW_FILE               32985
#define ID_FILE_SENDPAGEBYEMAIL         32986
#define ID_FILE_QUICKSAVE               32987
#define ID_FILE_SENDLINKBYEMAIL         32988
#define ID_RFAV_RENAME                  32989
#define ID_TOOLS_SETBG                  32991
#define ID_TOOLS_SELBG                  32992
#define ID_HELP_VISITDEVELOPERSFORUM    32993
#define ID_HISFOLDER_DELETE             32994
#define ID_HISURL_DELETE                32995
#define ID_HISURL_ADDTOFAVORITES        32996
#define ID_HISURL_PROPERTIES            32997
#define ID_OPTIONS_EXPORTPROXYLIST      32998
#define ID_OPTIONS_IMPORTPROXYLIST      32999
#define ID_TOOLS_MEM                    33000
#define ID_VIEW_ENCODING_JANESEEUC      33001
#define ID_VIEW_ENCODING_JANESEAUTO     33002
#define ID_TOOLS_AUTOREF                33004
#define ID_TOOLS_REFFRE                 33005
#define ID_RTAB_AUTOREF                 33006
#define ID_RTAB_REFFRE                  33007
#define ID_VIEW_LOCK                    33008
#define ID_TOOLS_AUTOFILTER_CUR         33009
#define ID_TOOLS_ALL_BK                 33010
#define ID_TOOLS_QUICKSEARCH            33011
#define ID_TOOLS_SYNC                   33012
#define ID_SC_SAVEFORM                  33013
#define ID_SC_SAVEGENFORM               33014
#define ID_SC_FILLFORM                  33015
#define ID_TOOLS_COLLECT                33016
#define ID_OPTIONS_DOWNLOAD             33017
#define ID_TOOLS_CLEANADDR              33018
#define ID_ALL_PAGE_LINKS               33019
#define ID_TOOLS_AUTOSETBG              33020
#define ID_VIEW_ENCODING_AUTO           33021
#define ID_FILE_PROPERTY                33022
#define ID_SAVEAS_GROUP                 33023
#define ID_GROUP                        33024
#define ID_FILE_AUTOSAVE                33025
#define ID_TOOL_CLEANMyIE9FORM          33026
#define ID_RTAB_AUTOSAVE                33028
#define ID_RTAB_ADDALIAS                33029
#define ID_RTAB_ADDSC                   33030
#define ID_VIEW_WIN_PRE                 33031
#define ID_VIEW_WIN_NEXT                33032
#define ID_VIEW_WIN_CLOSEALL            33033
#define ID_VIEW_WIN_MIN                 33034
#define ID_VIEW_WIN_RESTORE             33035
#define ID_VIEW_WIN_CLOSE               33036
#define ID_TOOLS_MOUSE_SCR              33037
#define ID_TOOLS_URL_FILTER             33038
#define ID_TOOLS_BP                     33040
#define ID_VIEW_LOCKTOOLBAR             33041
#define ID_TOOLS_AUTOSCROLL_ALL         33043
#define ID_VIEW_DOWNLOAD                33044
#define ID_TOOLS_DOWNLOAD               33045
#define ID_TOOLS_SAVE_IMG               33045
#define ID_FILE_NEW_SELECT              33047
#define ID_OPTIONS_PLAY_ANIMATION       33048
#define ID_TOOLS_AUTOSCROLL_PAGE0       33053
#define ID_TOOLS_AUTOSCROLL_PAGE4       33054
#define ID_TOOLS_AUTOSCROLL_PAGE2       33055
#define ID_TOOLS_AUTOSCROLL_PAGE1       33056
#define ID_OPTIONS_USE_IE_PROXY         33059
#define ID_CLEAN_TYPED_SEARCH           33060
#define ID_RFAVFOLDER_ONLY              33061
#define ID_VIEW_ENCODING_KOREAN_AUTO    33062
#define ID_VIEW_ENCODING_KOREAN_EUC     33063
#define ID_VIEW_ENCODING_KOREAN_ISO     33064
#define ID_MENUITEM33065                33065
#define ID_MENUITEM33066                33066
#define ID_MENUITEM33067                33067
#define ID_MENUITEM33068                33068
#define ID_MENUITEM33069                33069
#define ID_MENUITEM33070                33070
#define ID_MENUITEM33071                33071
#define ID_MENUITEM33072                33072
#define ID_MENUITEM33073                33073
#define ID_MENUITEM33074                33074
#define ID_MENUITEM33075                33075
#define ID_MENUITEM33076                33076
#define ID_MENUITEM33077                33077
#define ID_MENUITEM33078                33078
#define ID_MENUITEM33079                33079
#define ID_MENUITEM33080                33080
#define ID_MENUITEM33081                33081
#define ID_MENUITEM33082                33082
#define ID_MENUITEM33083                33083
#define ID_MENUITEM33084                33084
#define ID_MENUITEM33085                33085
#define ID_MENUITEM33086                33086
#define ID_MENUITEM33087                33087
#define ID_MENUITEM33088                33088
#define ID_MENUITEM33089                33089
#define ID_MENUITEM33090                33090
#define ID_MENUITEM33091                33091
#define ID_RTAB_CLOSE_UNLOCK            33101
#define ID_TOOLS_EABLE_DUPFILTER        33102
#define ID_VIEW_AUTOHIDE                33103
#define ID_HELP_MAIL_TO                 33105
#define ID_TOOLS_MONITOR                33106
#define ID_TOOLS_SEARCH_TEXT            33108
#define ID_LAST_VISITED                 33109
#define ID_LAST_CLOSED                  33110
#define ID_FIND_SEARCH_BAR              33112
#define ID_HIGH_LIGHT_SEARCH_BAR        33113
#define ID_OPTIONS_MEMORY               33114
#define ID_OPTIONS_SPEED                33115
#define ID_OPTIONS_CLOCK                33116
#define ID_OPTIONS_WINS                 33117
#define ID_OPTIONS_FILTER               33118
#define ID_TOOLS_SKIN_DEFAULT           33119
#define ID_WINDOW_MANAGER               33120
#define ID_FILE_NEW_SELECTED_LINK       33122
#define ID_FILE_AUTOSAVE_ALL            33123
#define ID_FILE_NEW_CURRENT_HOME_PAGE   33124
#define ID_FILE_NEW_CURRENT_UP_PAGE     33125
#define ID_FILE_CLOSE_KIND              33127
#define ID_SC_SET_FORM_DATA             33128
#define ID_RTAB_CLOSE_KIND              33129
#define ID_RTAB_CLOSE_ALIKE_URL         33129
#define ID_VIEW_FONTS_INCREASE          33130
#define ID_VIEW_FONTS_DECREASE          33131
#define ID_RTAB_MARK_KIND               33134
#define ID_VIEW_MARK_KIND               33134
#define ID_RTAB_MARK                    33135
#define ID_VIEW_MARK                    33136
#define ID_TOOLS_NO_BACKGROUND          33137
#define ID_VIEW_SET_UNDO_CLOSE          33138
#define ID_TOOLS_CLEAN_UNDO_CLOSE       33139
#define ID_RTAB_ADDTO_IE                33140
#define ID_ADDTO_IE                     33140
#define ID_RTAB_CLOSE_ALIKE_TITLE       33142
#define ID_RTAB_CLOSE_ALL_LEFT          33143
#define ID_RTAB_CLOSE_ALL_RIGHT         33144
#define ID_RTAB_CLOSE_ALL_KEEP_CURRENT  33145
#define ID_OPTIONS_ALLOW_ANIMATE        33146
#define ID_OPTIONS_DISABLE_FLASH        33147
#define ID_TOOLS_SEARCH_CASE            33148
#define ID_TOOLS_SEARCH_WHOLE           33149
#define ID_VIEW_PAGESIZE_50             33151
#define ID_VIEW_PAGESIZE_100            33152
#define ID_VIEW_PAGESIZE_200            33153
#define ID_VIEW_PAGESIZE_ADD10          33154
#define ID_VIEW_PAGESIZE_DEC10          33155
#define ID_TOOLS_EXTERNAL_AUTORUN       33156
#define ID_VIEW_COMPLETELY_REFRESH      33157
#define ID_IMG_SHOW_URL                 33160
#define ID_URL_SHOW                     33160
#define ID_IMG_EDIT_URL                 33161
#define ID_IMG_COPY_URL                 33162
#define ID_IMG_FILTER_URL               33163
#define ID_URL_FILTER                   33163
#define ID_LINK_OPEN                    33168
#define ID_LINK_OPEN_ACTIVE             33169
#define ID_LINK_OPEN_JUMP               33170
#define ID_URL_OPEN_JUMP                33170
#define ID_LINK_OPEN_IE                 33171
#define ID_TEXT_SEARCH                  33175
#define ID_TEXT_AUTOSAVE                33179
#define ID_TEXT_SAVE                    33180
#define ID_TEXT_EDIT                    33181
#define ID_URL_EDIT                     33182
#define ID_URL_COPY                     33183
#define ID_URL_OPEN                     33184
#define ID_URL_OPEN_ACTIVE              33185
#define ID_URL_OPEN_IE                  33186
#define ID_TEXT_COPY                    33187
#define ID_TEXT_HIGH_LIGHT              33188
#define ID_TEXT_FIND                    33189
#define ID_TEXT_OPEN_LINKS              33190
#define ID_URL_ADDTO_FAV                33191
#define ID_TEXT_COLLECTOR               33192
#define ID_URL_COLLECTOR                33193
#define ID_TOOLS_SEARCH_DELETE          33194
#define ID_PROXY_IMPORT                 33195
#define ID_PROXY_EXPORT                 33196
#define ID_URL_OPEN_INACTIVE            33203
#define ID_RTAB_CLOSE_MARKED_URL        33204
#define ID_TOOLS_EXTERNAL_RUN           33205
#define ID_RTAB_SORTSAVE                33206
#define ID_FILE_AUTOSAVE_SORT           33208
#define ID_VIEW_SELECT_LANG             33209
#define ID_RTAB_NEW_WINDOW              33210
#define ID_GO_PAGE_UP                   33211
#define ID_GO_PAGE_DOWN                 33212
#define ID_GO_PAGE_TOP                  33213
#define ID_GO_PAGE_BOTTOM               33214
#define ID_FILE_CLOSE_ALIKE_URL         33215
#define ID_FILE_CLOSE_ALIKE_TITLE       33216
#define ID_FILE_CLOSE_ALL_LEFT          33217
#define ID_FILE_CLOSE_ALL_RIGHT         33218
#define ID_FILE_CLOSE_MARKED_URL        33219
#define ID_VIEW_PROTECT                 33220
#define ID_HIGHLIGHT_SELECTED_TEXT      33221
#define ID_FIND_NEXT_SELECTED_TEXT      33222
#define ID_FIND_PREV_SELECTED_TEXT      33223
#define ID_OPEN_LINK                    33225
#define ID_OPEN_LINK_ACTIVE             33226
#define ID_OPEN_LINK_DEACTIVE           33227
#define ID_NOT_SAVE_KEY                 33228
#define ID_URL_OPEN_OTHER_SIDE          33229
#define ID_URL_OPEN_FTP                 33230
#define ID_VIEW_FORBID_AUTO_NAV         33231
#define ID_RTAB_FORBID_AUTO_NAV         33232
#define ID_GO_PAGE_RIGHT                33233
#define ID_GO_PAGE_LEFT                 33234
#define ID_URL_SHOW_IMG                 33237
#define ID_RTAB_CLOSE_KEEPCUR           33238
#define ID_TOOLS_FLY_FILTER             33240
#define ID_TOOLS_DISDOWN_ACTIVEX        33241
#define ID_TOOLS_DIALOG_FILTER          33242
#define ID_EDIT_IMG_URL                 33245
#define ID_FILE_IMPORT_EXPORT           33247
#define ID_FAVORITES_RESET_ORDER        33248
#define ID_RTAB_ADDTOFLYFILTER          33249
#define ID_IMAGE_SAVEAS                 33250
#define ID_RFAV_REPLACE                 33252
#define ID_VIEW_TOP_MOST                33253
#define ID_GO_BACK_AND_CLOSE            33254
#define ID_OPTIONS_SET_DEFAULT          33255
#define ID_REDIT_PASTE_ENTER            33256
#define ID_REDIT_COPY                   33257
#define ID_REDIT_DELETE                 33258
#define ID_REDIT_UNDO                   33259
#define ID_REDIT_PASTE                  33260
#define ID_HELP_CUR_EVIL                33261
#define ID_INDICATOR_MSG                59143
#define ID_INDICATOR_PROCESS            59144
#define ID_INDICATOR_TOOLS              59145
#define ID_INDICATOR_CLOCK              59146
#define ID_INDICATOR_IP                 59147
#define ID_INDICATOR_BP                 59148
#define ID_INDICATOR_RES                59149
#define ID_INDICATOR_WINS               59150
#define ID_INDICATOR_FILTER             59151
#define ID_INDICATOR_DISP               59152
#define ID_GO_UP_PAGE                   60000
#define IDS_GO_UP_PAGE                  60001
#define IDS_SAVE_IMG                    61000
#define IDS_RMOUSE_DRAG                 61204
#define IDS_OPTIONS_ACTIVENEWWINDOW     61205
#define ID_COLLECTOR_MODE               61205
#define IDS_RMOUSE_GESTURE              61205
#define ID_RMOUSE_DRAG                  61206
#define ID_RMOUSE_GESTURE               61207
#define ID_INDICATOR_COLLECT            61208
#define ID_OPEN_CURSOR_LINE             61208
#define ID_COLLECTOR_CLEAR              61209
#define ID_COLLECTOR_TRANS              61210
#define IDS_IE_PROXY_SERVER             61211
#define ID_OPTION_BK_IMAGE              61211
#define ID_OPTION_EX_TOOL               61211
#define ID_SEARCH_OK                    61212
#define IDS_EX_SEARCH                   61213
#define ID_RUN_SCRIPT                   61213
#define ID_ADDRESS_OK                   61214
#define IDS_GO                          61214
#define IDS_CONFIRM_CLEAN_SEARCH        61215
#define ID_COLLECTOR_SAVE               61216
#define IDS_SELECT_FIRST                61217
#define ID_OPEN_SELECTED_TEXT           61217
#define IDS_TRAY                        61218
#define IDS_REG_HOTKEY_FAIL             61219
#define IDS_NAME_EXISTED                61220
#define IDS_GENERAL                     61221
#define IDS_WINDOW                      61222
#define IDS_TAB                         61223
#define IDS_DOWNLOAD                    61224
#define IDS_MOUSE                       61225
#define IDS_GESTURE                     61226
#define IDS_ELSE                        61227
#define IDS_COMMAND                     61228
#define IDS_DO_NOTHING                  61229
#define IDS_SCROLL_PAGE_UP              61230
#define IDS_SCROLL_PAGE_DOWN            61231
#define IDS_SCROLL_PAGE_TOP             61232
#define IDS_SCROLL_PAGE_BOTTOM          61233
#define IDS_CLOSE                       61234
#define IDS_PREV_TAB                    61235
#define IDS_NEXT_TAB                    61236
#define IDS_NEW_TAB                     61237
#define IDS_AUTO_SAVE                   61238
#define IDS_UP                          61239
#define IDS_DOWN                        61240
#define IDS_LEFT                        61241
#define IDS_RIGHT                       61242
#define IDS_UP_DOWN                     61243
#define IDS_LEFT_CLICK                  61243
#define IDS_UP_LEFT                     61244
#define IDS_LEFT_DBCLICK                61244
#define IDS_UP_RIGHT                    61245
#define IDS_MIDDLE_CLICK                61245
#define IDS_DOWN_UP                     61246
#define IDS_RIGHT_CLICK                 61246
#define IDS_DOWN_LEFT                   61247
#define IDS_DOWN_RIGHT                  61248
#define IDS_LEFT_UP                     61249
#define IDS_LEFT_DOWN                   61250
#define IDS_LEFT_RIGHT                  61251
#define IDS_RIGHT_UP                    61252
#define IDS_RIGHT_DOWN                  61253
#define IDS_RIGHT_LEFT                  61254
#define IDS_CLOSE_ALL                   61255
#define IDS_UNDOCLOSE                   61256
#define IDS_SHOW_HIDE                   61257
#define IDS_SOURCE_CODE                 61258
#define IDS_FULL_SCREEN                 61259
#define IDS_AUTO_HIDE_BAR               61260
#define IDS_LINK_LIST                   61261
#define IDS_OPEN_LINK                   61262
#define IDS_THANK_DONATE                61266
#define IDS_ABOUT                       61267
#define IDS_OPEN_LINK_ACTIVE            61267
#define ID_COLLECTOR_TXT                61268
#define ID_COLLECTOR_IMAGE              61269
#define ID_COLLECTOR_OUTPUT             61269
#define ID_COLLECTOR_FILTER             61270
#define ID_COLLECTOR_SCRIPT             61270
#define IDS_TIP_CLEAN                   61271
#define IDS_TOOLBAR                     61271
#define IDS_AUTO_POPUP_FILTER           61272
#define IDS_URL_FILTER                  61273
#define IDS_USER_LIST_FILTER            61274
#define IDS_MAX_COLLECTOR_TXT           61275
#define IDS_MAX_COLLECTOR_IMAGE         61276
#define IDS_MAX_COLLECTOR_OUTPUT        61276
#define IDS_MAX_COLLECTOR_FILTER        61277
#define IDS_MAX_COLLECTOR_SCRIPT        61277
#define IDS_CLOSE_ALL_EXCEPT_CUR        61278
#define IDS_REG_HOTKEY_OK               61279
#define IDS_REG_HOTKEY_NULL             61280
#define IDS_THANKS                      61281
#define IDS_TAB_STYLE                   61281
#define ID_LL_SELECT_ALL                61282
#define ID_LL_SELECT_NONE               61283
#define ID_LL_SELECT_UP                 61284
#define ID_LL_SELECT_DOWN               61285
#define ID_LL_SELECT_ODD                61286
#define ID_LL_SELECT_EVEN               61287
#define ID_LL_OPEN_SELECT               61288
#define ID_LL_CLOSE_SELECT              61289
#define ID_LL_COPY_URL                  61290
#define ID_LL_CLOSE                     61291
#define ID_LL_EDIT_URL                  61291
#define ID_LL_REFRESH                   61292
#define IDS_CLOSE_LOCK_CONF             61293
#define IDS_FILL_CURRENT_FORM           61294
#define IDS_NAME                        61295
#define IDS_URL                         61296
#define IDS_NEW_GROUP                   61297
#define IDS_SEARCH_ENGINE               61298
#define IDS_LINK_LIST_TITLE             61299
#define IDS_SPEED                       61300
#define IDS_ADD_GROUP                   61301
#define IDS_OPEN_GROUP                  61302
#define IDS_GROUPNAME_ERROR             61303
#define IDS_NO_SEARCH_ENGINE            61304
#define IDS_SEARCH_HELP                 61305
#define IDS_GROUP_NOT_EXIST             61305
#define IDS_NO_SEARCH_KEYWORD           61306
#define IDS_KEYWORD_COUNT               61307
#define IDS_HIGH_LIGHT                  61308
#define IDS_SAVE                        61308
#define IDS_FILTER                      61309
#define IDS_MY_OPTIONS                  61309
#define IDS_OPEN                        61310
#define IDS_KEY                         61310
#define IDS_PROXY_SERVER                61311
#define IDS_TRANS_PROXY                 61312
#define IDS_WEB_PROXY                   61313
#define IDS_NOT_FIND_KEY                61314
#define IDS_FIND_KEY_INDEX              61315
#define ID_EXIT_NOW                     61316
#define IDS_IE_PROXY                    61317
#define IDS_OPEN_SELECT_LINK            61318
#define IDS_OPEN_ROOT_PAGE              61319
#define IDS_OPEN_UP_PAGE                61320
#define IDS_SAVE_HTML                   61321
#define IDS_INPUT_URL_KIND              61321
#define IDS_INPUT_URL                   61321
#define IDS_THANK_YOU                   61322
#define IDS_NAME_NULL                   61323
#define IDS_URL_NULL                    61324
#define IDS_DATA                        61325
#define IDS_INPUT_ITEM_DATA             61326
#define IDS_CONFIRM_DO                  61327
#define IDS_CONFIRM_DELALL_FORMDATA     61327
#define IDS_SCRIPT_ERR                  61328
#define IDS_SCRIPT_RUN_ERR              61329
#define IDS_SCRIPT_RUN_OK               61330
#define IDS_NOT_SELECT_SCRIPT           61331
#define IDS_INPUT_STICK_NAME            61332
#define IDS_INPUT_TITLE                 61332
#define IDS_CONFIRM_DOWNLOADING         61333
#define IDS_NOT_DRAG_SCRIPT             61334
#define IDS_NOT_SELECT_TEXT             61335
#define IDS_NOT_VALID_URL               61336
#define IDS_TITLE                       61337
#define IDS_DONATED                     61338
#define IDS_UNDONATED                   61339
#define IDS_MENU                        61341
#define IDS_START_CLOSE                 61342
#define IDS_DELETE                      61343
#define IDS_CONFIRM                     61344
#define IDS_STATUSBAR                   61345
#define IDS_INPUT_KEYWORD               61346
#define IDS_COLLECTOR                   61347
#define IDS_NONE                        61348
#define IDS_TIP_01URL                   61349
#define IDS_TIP_BROWSE                  61350
#define IDS_TIP_URL                     61351
#define IDS_TIP_PROTECT                 61352
#define IDS_TIP_ADDTO_CONTENT_FILTER    61353
#define IDS_TIP_TEXT                    61354
#define IDS_TIP_OPEN_FTP_ERR            61355
#define IDS_LAST_VISITING_PAGES         61356
#define IDS_LAST_CLOSED_PAGES           61357
#define IDS_VISITING_PAGES              61358
#define IDS_CLOSED_PAGES                61359
#define IDS_NEWS                        61360
#define IDS_TECH                        61361
#define IDS_AMUSE                       61362
#define IDS_NEW_DIR                     61363
#define IDS_INTERNAL_LANG               61364
#define IDS_FILENAME                    61365
#define IDS_LANGUAGE                    61366
#define IDS_VERSION                     61367
#define IDS_ICON                        61368
#define IDS_NOT_FIND                    61369
#define IDS_DIALOG_FILTER               61370
#define IDS_HELP_MAIL                   61371
#define IDS_DO_YOU_WANT                 61372
#define ID_ENABLE_FILTER                61373
#define IDS_POPUP_FILTER                61374
#define IDS_CONTENT_FILTER              61375
#define IDS_STR_DONATE                  61376
#define IDS_YOUR_NAME                   61377
#define IDS_RIGHT_BUTTON_TIP_GESTURE    61378
#define IDS_RIGHT_BUTTON_TIP_DRAG       61379
#define IDS_STARTUP_STATUS              61380
#define IDS_BLOCKED_MSG_PAGE            61381
#define IDS_TITILE_UNCHANGE             61382
#define IDS_QUICK_LINKS_FOLDER_NAME     61383
#define IDS_VERSION_INTERNAL            61384
#define IDS_EDIT_UNDOCLOSE              61385
#define IDS_VIEW_AUTOHIDE               61386
#define IDS_TOOLS_ALL                   61387
#define IDS_OPTIONS_MyIE9OPTIONS        61388
#define IDS_GO_BACK                     61389
#define ID_TOP_CLOSE                    61390
#define IDS_TOP_CLOSE                   61391
#define IDS_MSG_PATH_NOT_EXIST          61392
#define IDS_MSG_SET_IE_PATH_OK          61393
#define IDS_MSG_SET_IE_PATH_FAILED      61394
#define IDS_MSG_GET_IE_PATH_FAILED      61395
#define IDS_OLD_QUICK_LINKS_FOLDER_NAME 61396
#define IDS_FLY_FILTER                  61397
#define IDS_HOMEPAGE                    61398
#define IDS_SOFTWARE_FORUM              61399
#define IDS_DEFAULT_FAV_PATH            61400
#define IDS_COMFIRM_IE8MODE             61401
#define IDS_FAV_ASK                     61402
#define IDS_X_TIP_CLOSE_ALL_RIGHT       61403
#define IDS_RIGHT_DBCLICK               61404
#define IDS_FAKE_AS_IE                  61405
#define IDS_SYS_X_TIP                   61406
#define IDS_SYS_X_TIP_SETTED            61407
#define IDS_OVERWRITE_FORM              61408
#define IDS_NO_DATA_NEED_TO_SAVE        61409
#define IDS_FAILED_TO_SAVE_FORM         61410
#define IDS_OVERWRITE_FIELD             61411
#define IDS_TITLE_FORM_URL              61412
#define IDS_PAGE_LASTVISIT              61413
#define IDS_PAGE_OPEN                   61414
#define IDS_PAGE_TYPED                  61415
#define IDS_PAGE_FAV                    61416
#define IDS_PAGE_FORM                   61417
#define IDS_SC_FILLFORM                 61418
#define IDS_RESTORE_CONFIG              61419
#define IDS_RESTORED                    61420
#define IDS_ASK_CONFIRM                 61421
#define IDS_ADDED_BADSITE               61422

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        334
#define _APS_NEXT_COMMAND_VALUE         33262
#define _APS_NEXT_CONTROL_VALUE         1485
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
